In [7]:
import numpy as np
import random

In [48]:
#Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.
a = np.arange(1, 11)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [4]:
#Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.
B = np.zeros((3, 3), dtype = int)
print(B)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [8]:
#Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.
C = np.zeros((3, 3), dtype = int)
for i in range(3):
    for j in range(3):
        C[i,j] = random.randint(1, 10)
print(C)

[[ 7  4 10]
 [10  2  2]
 [ 7  3  3]]


In [10]:
#Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.
D = np.random.random((4, 4))
print(D)

[[0.0937464  0.53493614 0.26143674 0.66575813]
 [0.08922948 0.11772865 0.58988397 0.05745831]
 [0.78681477 0.72197007 0.2341017  0.75748605]
 [0.80933572 0.77367389 0.04707355 0.32526573]]


In [17]:
#Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.
e = np.random.randint(11, size=5)
f = np.random.randint(11, size=5)
print(f"E = {e}")
print(f"F = {f}")
print(f"e+f = {e+f}")
print(f"e-f = {e-f}")
print(f"f-e = {f-e}")
print(f"e*f = {e*f}")
print(f"e*f = {e*f}")

E = [2 7 1 2 9]
F = [7 8 2 2 8]
e+f = [ 9 15  3  4 17]
e-f = [-5 -1 -1  0  1]
f-e = [ 5  1  1  0 -1]
e*f = [14 56  2  4 72]


In [19]:
#Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.
g = np.random.randint(20, size=7)
h = np.random.randint(20, size=7)
mul = np.dot(g, h)
print(f"G - {g}, h - {h}, mul = {mul}")

G - [ 6  8 17  3  0 15  2], h - [ 7 14  6 10  3 12  5], sum = 476


In [26]:
#Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.
I = np.random.randint(11, size=(2, 2))
J = np.random.randint(11, size=(2, 3))
print(f"I - {I}, \nJ - {J}, \nmul = {np.dot(I, J)}")

I - [[2 1]
 [2 0]], 
J - [[6 4 0]
 [4 2 2]], 
mul = [[16 10  2]
 [12  8  0]]


In [28]:
#Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.
K = np.random.randint(11, size=(3, 3))
K_inv = np.linalg.inv(K)
print(f"K - {K},\nK_inv - {K_inv}")

K - [[7 6 7]
 [9 0 7]
 [0 2 5]],
K_inv - [[ 0.05785124  0.0661157  -0.17355372]
 [ 0.18595041 -0.1446281  -0.05785124]
 [-0.07438017  0.05785124  0.2231405 ]]


In [29]:
#Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.
L = np.random.random((4, 4))
print(f"L - {L},\nL(T) - {L.T}") 

L - [[0.05563671 0.92935629 0.72745435 0.44073341]
 [0.10348231 0.81629798 0.07517253 0.9310348 ]
 [0.14774743 0.54771876 0.82717152 0.01007997]
 [0.49836547 0.75404217 0.87819087 0.73343593]],
L(T) - [[0.05563671 0.10348231 0.14774743 0.49836547]
 [0.92935629 0.81629798 0.54771876 0.75404217]
 [0.72745435 0.07517253 0.82717152 0.87819087]
 [0.44073341 0.9310348  0.01007997 0.73343593]]


In [30]:
#Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.
M = np.random.randint(11, size=(3, 4))
n = np.random.randint(11, size=4)
mul = np.dot(M, n)
print(f"M - {M},\nn - {n},\nmul = {mul}")

M - [[ 4  3  6  4]
 [ 9 10  8  9]
 [ 6  4  6  5]],
n - [5 9 9 3],
mul = [113 234 135]


In [31]:
#Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.
O = np.random.random((2, 3))
p = np.random.random((3, ))
mul = np.dot(O, p)
print(f"O - {O},\np - {p},\nmul = {mul}")

O - [[0.50968398 0.23658982 0.61857493]
 [0.21272984 0.2924794  0.82889749]],
p - [0.42612616 0.50157388 0.28537119],
mul = [0.51238041 0.47389324]


In [32]:
#Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.
Q = np.random.randint(11, size=(2, 2))
R = np.random.randint(11, size=(2, 2))
print(f"Q - {Q},\nR - {R},\nmul = {Q*R}")

Q - [[ 9  2]
 [10  3]],
R - [[ 3  7]
 [ 1 10]],
mul = [[27 14]
 [10 30]]


In [33]:
#Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.
S = np.random.randint(11, size=(2, 2))
T = np.random.randint(11, size=(2, 2))
print(f"S - {S},\nT - {T},\nmul = {np.dot(Q,R)}")

S - [[6 7]
 [1 3]],
T - [[1 2]
 [6 4]],
mul = [[ 29  83]
 [ 33 100]]


In [35]:
#Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.
U = np.random.randint(101, size=(5, 5))
print(f"U - {U},\nsum = {U.sum()}")

U - [[17  3 64 64 43]
 [19 12 74 76 80]
 [59 90 52 73 25]
 [40 51  1 47 45]
 [11 88 75  1 64]],
sum = 1174


In [36]:
#Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.
V = np.random.randint(11, size=(4, 4))
W = np.random.randint(11, size=(4, 4))
print(f"V - {V},\nW - {W},\ndiv = {V-W}") 

V - [[10  4  6  8]
 [ 9  2  5  4]
 [ 3  8  4  3]
 [ 6  2  6  3]],
W - [[ 5  3 10  5]
 [ 3  6  4 10]
 [ 2  7  4  6]
 [ 3  4  3 10]],
div = [[ 5  1 -4  3]
 [ 6 -4  1 -6]
 [ 1  1  0 -3]
 [ 3 -2  3 -7]]


In [52]:
#Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.
X = np.random.random((3, 3))
sum1 = X[0,:].sum()
sum2 = X[1,:].sum()
sum3 = X[2,:].sum()
res = np.array([sum1, sum2, sum3])
print(f"X - {X},\nvector - {res.reshape(3, 1)}")

X - [[0.61149705 0.49326609 0.13567248]
 [0.55437154 0.29114995 0.54833446]
 [0.37264947 0.16986782 0.58350138]],
vector - [[1.24043563]
 [1.39385596]
 [1.12601867]]


In [46]:
#Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.
Y = np.random.randint(11, size=(3, 4))
res = Y*Y
print(f"Y - {Y},\nY^2 - {res}")

Y - [[ 4  2  7  8]
 [ 9 10  7  2]
 [ 1  7  9  3]],
Y^2 - [[ 16   4  49  64]
 [ 81 100  49   4]
 [  1  49  81   9]]


In [47]:
#Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.
z = np.random.randint(51, size=4)
res = np.sqrt(z)
print(f"z - {z},\nsqrt - {res}")

z - [21 45 22 21],
sqrt - [4.58257569 6.70820393 4.69041576 4.58257569]
